"use client";
import { FormEvent, useEffect, useState } from 'react';
import { Workspace } from '@/components/workspace';
import { api } from '@/lib/api';
import { AdminOperations } from '@/components/admin-operations';
import { AdminAccess } from '@/components/admin-access';
type Entry={key:string;payload:{headline:string;summary:string;strengths:string[];challenges:string[];relationships:string[]};status:string;version:number};
function Editor(){
  const [items,setItems]=useState<Entry[]>([]),[key,setKey]=useState(''),[headline,setHeadline]=useState(''),[summary,setSummary]=useState(''),[strengths,setStrengths]=useState(''),[challenges,setChallenges]=useState(''),[relationships,setRelationships]=useState(''),[status,setStatus]=useState('draft'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[allowed,setAllowed]=useState(false),[logs,setLogs]=useState<unknown[]>([]);
  useEffect(()=>{api<Entry[]>('/admin/knowledge').then(rows=>{setItems(rows);setAllowed(true);}).catch(e=>setMessage(e.message));},[]);
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{await api('/admin/knowledge',{key,status,payload:{headline,summary,strengths:strengths.split('\n').filter(Boolean),challenges:challenges.split('\n').filter(Boolean),relationships:relationships.split('\n').filter(Boolean)}});setItems(await api<Entry[]>('/admin/knowledge'));setMessage('Шинэ хувилбарыг хадгаллаа.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  function select(e:Entry){setKey(e.key);setHeadline(e.payload.headline);setSummary(e.payload.summary);setStrengths(e.payload.strengths.join('\n'));setChallenges(e.payload.challenges.join('\n'));setRelationships(e.payload.relationships.join('\n'));setStatus(e.status);}
  return <><h1>Мэдлэгийн редакц</h1>{message&&<p className="status" role="status">{message}</p>}{allowed&&<><p>Зөвхөн батлагдсан мэдлэг хувийн тайлалд хэрэглэгдэнэ. planet_0_sign_0, planet_0_house_1, aspect_0_1_trine, transit_2_1_square хэлбэрийн түлхүүр ашиглана.</p><div className="data-grid"><section>{items.map(e=><article className="reading-block" key={e.key}><button className="text-button" onClick={()=>select(e)}>{e.key} · v{e.version} · {e.status}</button></article>)}</section><form className="editor" onSubmit={save}><label>Түлхүүр<input value={key} onChange={e=>setKey(e.target.value)} pattern="[a-z0-9_]{1,100}" required/></label><label>Гарчиг<input value={headline} onChange={e=>setHeadline(e.target.value)} maxLength={200} required/></label><label>Тайлбар<textarea value={summary} onChange={e=>setSummary(e.target.value)} rows={6} maxLength={2000} required/></label><label>Давуу тал — мөр бүрд нэг<textarea value={strengths} onChange={e=>setStrengths(e.target.value)}/></label><label>Анхаарах зүйл<textarea value={challenges} onChange={e=>setChallenges(e.target.value)}/></label><label>Харилцаа<textarea value={relationships} onChange={e=>setRelationships(e.target.value)}/></label><label>Төлөв<select value={status} onChange={e=>setStatus(e.target.value)}><option value="draft">Ноорог</option><option value="review">Хяналт</option><option value="approved">Батлагдсан</option><option value="archived">Архив</option></select></label><button disabled={busy} className="button primary">Хадгалах</button></form></div><section className="reading-block"><h2>Үйл ажиллагааны бүртгэл</h2><button className="button outline" onClick={()=>api<unknown[]>('/admin/logs').then(setLogs).catch(e=>setMessage(e.message))}>Сүүлийн 100 үйлдэл</button><pre style={{overflow:'auto'}}>{JSON.stringify(logs,null,2)}</pre></section></>}</>;
}
export default function Admin(){return <Workspace><AdminAccess><Editor/><AdminOperations/></AdminAccess></Workspace>;}
