import Image from "next/image";
import Link from "next/link";
import { asset } from "@/lib/paths";
import { HeroArt } from "@/components/hero-art";
import { ChartPreview } from "@/components/chart-preview";
import { ZodiacGallery } from "@/components/zodiac-gallery";

export default function Home() {
  return <main>
    <header className="site-header"><Link className="brand" href="/"><Image src={asset('/assets/brand/mark.svg')} alt="" width={44} height={44}/><span><b>ОД ТОЙРОГ</b><small>Таны төрсөн мөчийн тэнгэр.</small></span></Link><nav aria-label="Үндсэн цэс"><Link href="/chart">Натал зураг</Link><Link href="/learn">Мэдлэг</Link><a href="#story">Бидний тухай</a></nav><Link className="button outline" href="/auth">Нэвтрэх</Link></header>
    <section className="hero landscape-hero"><HeroArt/><div className="hero-copy"><p className="eyebrow">ӨӨРИЙГӨӨ УНШИХ ШИНЭ АРГА</p><h1>Таны төрсөн мөчийн<br/><em>тэнгэрийг нээнэ.</em></h1><p className="lead">Төрсөн огноо, цаг, газраа оруулж өөрийн натал зургаа нээнэ. Тэр мөчийн тэнгэрээс зан чанар, харилцаа, дотоод ертөнцийн холбоосыг уншина.</p><div className="hero-actions"><Link className="button primary" href="/onboarding">Натал зургаа нээх ✦</Link><a href="#idea" className="text-link">Од Тойргийг судлах ↓</a></div><div className="hero-note">Зурхай бол баттай зөгнөл биш.<br/>Өөрийгөө эргэцүүлэх нэгэн хэл.</div></div></section>
    <section className="idea section" id="idea"><div className="section-number">I</div><div><p className="eyebrow">НАРНЫ ОРДООС ЦААШ</p><h2>Таны зурлага<br/>нэг ордоос бүрдэхгүй.</h2></div><div className="idea-copy"><p>Натал зураг нь зөвхөн Нарны орд биш. Сар, гаригууд, ордон болон тэдгээрийн холбоос нийлж нэгэн бүтэн зураг болно.</p><Link className="text-link" href="/learn">Зургаа уншиж сурах →</Link></div></section>
    <section className="process section">{[['01','Төрсөн мөч','Огноо, цаг, төрсөн газраа оруулна.'],['02','Натал зураг','Гаригийн бодит байрлалыг тооцоолно.'],['03','Таны тайлал','Холбоос бүрийг монголоор уншина.']].map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</section>
    <section className="section preview-section"><p className="eyebrow">НАТАЛ ЗУРАГ</p><h2>Эхлээд таны гол гурав.</h2><p>Нар — үндсэн чиглэл. Сар — мэдрэмж. Асцендент — ертөнцтэй уулзах төрх.</p><ChartPreview/><Link href="/chart" className="button outline">Миний зураг →</Link></section>
    <section className="section preview-section"><p className="eyebrow">ӨНӨӨДРИЙН ТЭНГЭР</p><h2>Өдөр бүр шинэ өнцөг.</h2><p>Өнөөгийн гаригийн байрлалыг таны төрсөн үеийн зурагтай харьцуулна. Тайлбар бүрийн цаана байгаа холбоосыг “Яагаад?” хэсгээс харж болно.</p><Link href="/today" className="text-link">Өнөөдрийг унших →</Link></section>
    <section className="compatibility section"><Image src={asset('/assets/illustration/compatibility.webp')} alt="Хоёр тойргийн уулзвар — хослолын бэлгэдлийн зураг" width={1448} height={1086}/><div className="compat-copy"><p className="eyebrow">ХОЁР ЗУРГИЙН УУЛЗВАР</p><h2>Та хоёрын хооронд<br/>юу өрнөдөг вэ?</h2><p>Хослол нь “тохирно, тохирохгүй” гэсэн ганц хариулт биш. Сэтгэл, хайр, харилцааны ялгааг тус тусад нь судална.</p><Link href="/compatibility" className="button outline">Хосын зураг судлах</Link></div></section>
    <section className="story section" id="story"><Image src={asset('/assets/brand/primary-logo/od-toirog.webp')} alt="Оуроборосын тойрог доторх аялагч" width={500} height={500}/><div><p className="eyebrow">БЭЛГЭ ТЭМДГИЙН ТҮҮХ</p><h2>Аялал ба<br/>мөнхийн тойрог.</h2><p>Аялагч бол өөрийгөө нээхээр үл мэдэгдэх зүг рүү алхаж буй хүн. Оуроборос бол цаг хугацаа, өөрчлөлт, буцан ирэх хөдөлгөөн.</p><blockquote>Хүн илүү том тэнгэрийн тойрог дотор өөрийн замыг эхлүүлнэ.</blockquote></div></section>
    <section className="section zodiac-feature"><p className="eyebrow">ТЭНГЭРИЙН ТОЛЬ · I—XII</p><h2>Арван хоёр орд,<br/>арван хоёр өөр хэмнэл.</h2><p>Бэлгэдэл бүрийн цаадах санаа, харилцаа, дотоод ертөнцийн сэдвийг судлаарай.</p><ZodiacGallery/><Link className="text-link" href="/zodiac">Ордын толь руу →</Link></section>
    <section className="final-cta"><span className="final-star">✦</span><h2>Таны төрсөн мөчийн<br/>тэнгэр ямар байсан бэ?</h2><Link className="button primary" href="/onboarding">Натал зургаа нээх</Link></section>
    <footer><Link className="brand" href="/">ОД ТОЙРОГ</Link><p>Зурхайн тайлал нь бэлгэдлийн уламжлал, өөрийгөө эргэцүүлэх арга бөгөөд баттай зөгнөл биш.</p><Link href="/learn">Мэдлэг</Link><Link href="/privacy">Нууцлал</Link></footer>
  </main>;
}
