"use client";
import { useState } from 'react';
import { api } from '@/lib/api';
import { mn } from '@/lib/mn';
type Setting={key:string;version:number;payload:Record<string,unknown>};
export function AdminOperations(){
  const [records,setRecords]=useState<unknown[]>([]),[title,setTitle]=useState(''),[error,setError]=useState(''),[settings,setSettings]=useState<Setting[]>([]),[selected,setSelected]=useState(''),[text,setText]=useState(''),[busy,setBusy]=useState(false);
  async function load(key:string,label:string){setError('');setTitle(label);try{setRecords(await api<unknown[]>(`/admin/records/${key}`));}catch(e){setError((e as Error).message);}}
  async function configure(){setError('');try{setSettings(await api<Setting[]>('/admin/settings'));setError('Эдгээр нь Swiss / Placidus аргын тохиргоо. JPL v0.1 нь тусдаа, checksum-тай дүрмийн файл ашиглана.');}catch(e){setError((e as Error).message);}}
  async function save(){setBusy(true);setError('');try{await api('/admin/settings',{key:selected,payload:JSON.parse(text)});await configure();setError('Шинэ хувилбар хадгалагдлаа.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="reading-block"><h2>Үйлчилгээний удирдлага</h2><div className="tabs">{[['users','Хэрэглэгчид'],['readings','Тайллууд'],['knowledge_versions','Мэдлэгийн хувилбарууд'],['prompt_versions','Промпт ба дүрмийн хувилбарууд'],['analytics','Аналитик үйлдлүүд'],['failures','Амжилтгүй үүсгэлт'],['reports','Хослолын тайлан'],['subscriptions','Захиалгууд']].map(([key,label])=><button key={key} onClick={()=>load(key,label)}>{label}</button>)}</div>{title&&<><h3>{title}</h3><p className="muted">Сүүлийн 100 хүртэл бичлэг. Хэрэглэгчдийн эхний 50 бүртгэл.</p>{records.map((record,i)=><details key={i}><summary>Бичлэг {i+1}</summary><pre style={{overflow:'auto'}}>{JSON.stringify(record,null,2)}</pre></details>)}</>}<details><summary>Нэр томьёоны лавлах</summary><p>Хяналттай нэршил. Нийтийн интерфейсийн хувилбартай хамт шинэчилнэ.</p>{mn.planets.map((name,i)=><p key={name}>{i} — {name}</p>)}<p>{mn.signs.join(' · ')}</p></details><button className="button outline" onClick={configure}>Промпт, орб ба жин тохируулах</button>{settings.length>0&&<div className="editor"><label>Тохиргоо<select value={selected} onChange={e=>{setSelected(e.target.value);setText(JSON.stringify(settings.find(s=>s.key===e.target.value)?.payload||{},null,2));}}><option value="">Сонгох</option>{settings.map(s=><option key={s.key} value={s.key}>{s.key==='astrology'?'Натал / транзит / хослолын дүрэм':'Хэлний промпт'} · v{s.version}</option>)}</select></label>{selected&&<><label>JSON тохиргоо<textarea value={text} onChange={e=>setText(e.target.value)} rows={18}/></label><button className="button primary" disabled={busy} onClick={save}>Шинэ хувилбар хадгалах</button></>}</div>}{error&&<p role="status" className="status">{error}</p>}</section>;
}
